import Head from "next/head";
import styles from "../styles/Home.module.css";
import { equipos } from "../assets/data";
import ProductList from "../components/ProductList";
import Footer from "../components/Footer";
import NavBar from "../components/NavBar";

export const getStaticProps = async () => {
  return {
    props: {
      equiposList: equipos,
    },
  };
};

export default function Home(equiposList) {
  return (
    // <div className={styles.container}>
    <div>
      <Head>
        <title>Dinpa Medical</title>
        <meta name="description" content="Generated by Dinipa" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <ProductList equiposList={equiposList.equiposList} />
      </main>

      <Footer />
    </div>
  );
}
